[package]
name = "catalog"
version = "0.1.0"
edition = "2024"

[dependencies]
serde.workspace = true
spec.workspace = true
eyre.workspace = true
catalog-berachain.workspace = true
catalog-ethereum.workspace = true
catalog-polygon.workspace = true
catalog-tempo.workspace = true
