[package]
name = "catalog-ethereum"
version = "0.1.0"
edition = "2024"

[dependencies]
serde.workspace = true
spec.workspace = true
eyre.workspace = true
tinytemplate.workspace = true
serde_json.workspace = true
template.workspace = true
getrandom.workspace = true

[lib]
path = "lib.rs"
