[package]
name = "babel-api"
version = "0.1.0"
edition = "2021"

[dependencies]
jsonrpsee = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
eyre = { workspace = true }
tracing = "0.1"
